apiVersion: apps/v1
kind: Deployment
metadata:
  name: apache-html-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apache-html
  template:
    metadata:
      labels:
        app: apache-html
    spec:
      containers:
      - name: apache-html-container
        image: srikanth7777/apache-html-sample:2
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: 300m
          requests:
            cpu: 200m
