apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  name: apache-html-deployment
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: apache-html
  type: LoadBalancer
status:
  loadBalancer: {}
