apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: postgres-pod
    vote: vote_demo
  name: postgres-pod
spec:
  containers:
  - image: postgres
    name: postgres
    ports:
      - containerPort: 5432
    env:
      - name: POSTGRES_USER
        value: "postgres"
      - name: POSTGRES_PASSWORD
        value: "postgres"
