apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: db
    vote: vote_demo
  name: db
spec:
  containers:
  - image: postgres
    name: db
    ports:
      - containerPort: 5432
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}