apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    name: redis
    vote: vote_demo
  name: redis
spec:
  containers:
  - image: redis
    name: redis
    ports:
    - containerPort: 6379
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
