apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: redis
    vote: vote_demo
  name: redis
  namespace: votingapp
spec:
  ports:
  - port: 6379
    protocol: TCP
    targetPort: 6379
  selector:
    name: redis
    vote: vote_demo
status:
  loadBalancer: {}
