apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: voteresult
    vote: vote_demo
  name: voteresult
  namespace: votingapp
spec:
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 5000
    nodePort: 30005
  selector:
    name: voteresult
    vote: vote_demo
  type: NodePort
status:
  loadBalancer: {}
