apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: voteresult
    vote: vote_demo
  name: voteresult
spec:
  containers:
          - image: kodekloud/examplevotingapp_result:v1
            ports:
            - containerPort: 80
    name: voteresult
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}