apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    name: voteapp
    vote: vote_demo
  name: voteapp
  namespace: votingapp
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30004
  selector:
    name: voteapp
    vote: vote_demo
  type: NodePort
status:
  loadBalancer: {}
