apiVersion: apps/v1

kind: Deployment

metadata:

  name: html-app-deployment

  labels:

    app: html-app

spec:

  replicas: 3

  selector:

    matchLabels:

      app: html-app

  template:

    metadata:

      labels:

        app: html-app

    spec:

      containers:

      - name: html-app

        image: srikanth7777/deploy-webapp:4


