apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-webapp
spec:
  replicas: 3
  selector:
    matchLabels:
      app: test-webapp
  template:
    metadata:
      labels:
        app: test-webapp
    spec:
      containers:
      - name: test-webapp
        image: srikanth7777/deploy-webapp:3
        ports:
        - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: test-webapp-service
spec:
  selector:
    app: test-webapp
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
