apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: html-app
  name: html-app-deployment
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 80
  selector:
    app: html-app
  type: NodePort
status:
  loadBalancer: {}
